apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: pragnya
  labels:
    app: deploy
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy
    spec:
      imagePullSecrets:  # Add the imagePullSecrets field
        - name: mysecretfile  # Name of the secret created
      containers:
        - name: deploy
          image: pragnya.azurecr.io/kube:1.0.3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:  # Move limits inside the resources block
              cpu: 100m
              memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10