apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: pragnya
  labels:
    app: deploy
spec:
  selector:
    matchLabels:
      app: deploy
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: deploy
    spec:
      # initContainers:
      # Init containers are exactly like regular containers, except:
      # - Init containers always run to completion.
      # - Each init container must complete successfully before the next one starts.
      imagePullSecrets:
        - name: mysecret  # Move imagePullSecrets to this location
      containers:
        - name: deploy
          image: pragnya.azurecr.io/kube:1.0.3
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /_status/healthz
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 2
            successThreshold: 1
            failureThreshold: 3
            periodSeconds: 10